In [1]:
from tqdm.notebook import tqdm
import pandas as pd
import pickle
import numpy as np

# wiki_data

In [2]:
with open('./source/wiki_data.pickle', 'rb') as handle:
    wiki_table_df = pickle.load(handle)

In [15]:
# for i in wiki_table_df:
#     if (i[3] == 'arts'):
#         print (i[0])
#         print (i[1])
#         print (i[2])
# #         break

In [21]:
len(wiki_table_df)

1002

In [9]:
wiki_table_df[5][3]

'arts'

In [63]:
np.array(flatten_cells)

array([ 0, 45, 45, 38,  0, 45, 45, 38,  0, 45, 39, 38,  0, 45, 39, 38,  0,
       45, 42, 38,  0, 45, 46, 38,  0, 45, 46, 38,  0, 45, 46, 38,  0, 45,
       46, 38,  0, 45, 46, 38,  0, 44, 22, 22])

In [67]:
cells = wiki_table_df[0][2]
flatten_cells = [len(i) for rows in cells for i in rows]
flatten_cells = np.array(flatten_cells)
flatten_cells = flatten_cells[flatten_cells > 0]
max(flatten_cells)
sum(flatten_cells)/len(flatten_cells)
np.var(flatten_cells)

34.7346189164371

In [89]:
wiki_dict = {
    'num_col':[],
    'num_row':[],
#     'max_rows': [],
#     'max_rows': [],
    'max_cell_length': [],
    'avg_length': [],
    'length_variance':[],
    
    'pg_title': [],
    'section_title': [],
    'table_caption': [],
    'columns': [],
    'values': [],
#     'X': [],
    'y': []
}

for wiki_row in wiki_table_df:
    wiki_dict['num_col'].append(wiki_row[0]['num_col'])
    wiki_dict['num_row'].append(wiki_row[0]['num_row'])
    
    cells = wiki_row[2]
    flatten_cells = [len(i) for rows in cells for i in rows]
    flatten_cells = np.array(flatten_cells)
    flatten_cells = flatten_cells[flatten_cells > 0]
    if flatten_cells.shape == (0,):
        wiki_dict['max_cell_length'].append(0)
        wiki_dict['avg_length'].append(0)
        wiki_dict['length_variance'].append(0)
    else:
        wiki_dict['max_cell_length'].append(max(flatten_cells))
        wiki_dict['avg_length'].append(sum(flatten_cells)/len(flatten_cells))
        wiki_dict['length_variance'].append(np.var(flatten_cells))

    wiki_dict['pg_title'].append(wiki_row[0]['pg_title'])
    wiki_dict['section_title'].append(wiki_row[0]['section_title'])
    if 'table_caption' in wiki_row[0]:
        wiki_dict['table_caption'].append(wiki_row[0]['table_caption'])
    else:
        wiki_dict['table_caption'].append('')

    wiki_dict['columns'].append(' '.join(wiki_row[1]))
    values = [item for sublist in wiki_row[2] for item in sublist]
    wiki_dict['values'].append(' '.join(values))
    wiki_dict['y'].append(wiki_row[3])

In [91]:
for key, value in wiki_dict.items():
    print (key, len(value))

num_col 1002
num_row 1002
max_cell_length 1002
avg_length 1002
length_variance 1002
pg_title 1002
section_title 1002
table_caption 1002
columns 1002
values 1002
y 1002

In [94]:
wiki_df = pd.DataFrame.from_dict(wiki_dict)

In [95]:
wiki_df['X'] = wiki_df['pg_title'] + ' ' +\
               wiki_df['section_title'] + ' ' +\
               wiki_df['table_caption'] + ' ' +\
               wiki_df['columns'] + ' ' +\
               wiki_df['values'] # + ' ' +\
#                wiki_df['y']

In [96]:
with open('./source/wiki_df.pickle', 'wb') as handle:
    pickle.dump(wiki_df, handle)

In [97]:
wiki_df

,num_col,num_row,max_cell_length,avg_length,length_variance,pg_title,section_title,table_caption,columns,values,y,X
0,4,11,46,41.151515,34.734619,Mid Antrim (Northern Ireland Parliament consti...,Members of Parliament,Members of Parliament,Election Election Member Party,"1929, Northern Ireland general election, 1929...",society,Mid Antrim (Northern Ireland Parliament consti...
1,2,1,18,18.000000,0.000000,Whispermoon,,Track listing,Professional ratings Professional ratings Revi...,"Allmusic, Allmusic",arts,Whispermoon Track listing Professional rating...
2,2,6,33,13.583333,52.243056,Khalsa Diwan Society Vancouver,First executive committee,First executive committee,Title Person,President Bhai Sewa Singh Vice President Bhai ...,society,Khalsa Diwan Society Vancouver First executive...
3,2,7,39,20.142857,355.693878,Julien Leparoux,Year-end charts,Year-end charts,Chart (2006â€“present) Peak position,National Earnings List for Jockeys 2006 8 Nati...,sports,Julien Leparoux Year-end charts Year-end chart...
4,5,2,34,13.750000,121.187500,Real Voice,Charts,Charts,Release Chart Peak Position Sales Total Chart Run,28 February 2007 Oricon Weekly Singles Chart W...,arts,Real Voice Charts Charts Release Chart Peak Po...
...,...,...,...,...,...,...,...,...,...,...,...,...
997,4,19,62,33.447368,311.931440,2009 US Open (tennis),Day 3 (September 2),Day 3 (September 2),Matches on Main Courts Matches on Main Courts ...,"Women's Singles 2nd Round, 2009 US Open â€“ Wo...",sports,2009 US Open (tennis) Day 3 (September 2) Day ...
998,4,19,83,35.184211,361.097645,2009 US Open (tennis),Day 4 (September 3),Day 4 (September 3),Matches on Main Courts Matches on Main Courts ...,"Women's Singles 2nd Round, 2009 US Open â€“ Wo...",sports,2009 US Open (tennis) Day 4 (September 3) Day ...
999,4,18,64,34.569444,311.800733,2009 US Open (tennis),Day 5 (September 4),Day 5 (September 4),Matches on Main Courts Matches on Main Courts ...,"Women's Singles 3rd Round, 2009 US Open â€“ Wo...",sports,2009 US Open (tennis) Day 5 (September 4) Day ...
1000,4,18,71,35.222222,312.783951,2009 US Open (tennis),Day 6 (September 5),Day 6 (September 5),Matches on Main Courts Matches on Main Courts ...,"Men's Singles 3rd Round, 2009 US Open â€“ Men'...",sports,2009 US Open (tennis) Day 6 (September 5) Day ...
1001,4,18,71,36.125000,351.220486,2009 US Open (tennis),Day 7 (September 6),Day 7 (September 6),Matches on Main Courts Matches on Main Courts ...,"Women's Singles 4th Round, 2009 US Open â€“ Wo...",sports,2009 US Open (tennis) Day 7 (September 6) Day ...

In [18]:
wiki_df['y']

,pg_title,section_title,table_caption,columns,values,y,X
0,Mid Antrim (Northern Ireland Parliament consti...,Members of Parliament,Members of Parliament,Election Election Member Party,"1929, Northern Ireland general election, 1929...",society,Mid Antrim (Northern Ireland Parliament consti...
1,Whispermoon,,Track listing,Professional ratings Professional ratings Revi...,"Allmusic, Allmusic",arts,Whispermoon Track listing Professional rating...
2,Khalsa Diwan Society Vancouver,First executive committee,First executive committee,Title Person,President Bhai Sewa Singh Vice President Bhai ...,society,Khalsa Diwan Society Vancouver First executive...
3,Julien Leparoux,Year-end charts,Year-end charts,Chart (2006â€“present) Peak position,National Earnings List for Jockeys 2006 8 Nati...,sports,Julien Leparoux Year-end charts Year-end chart...
4,Real Voice,Charts,Charts,Release Chart Peak Position Sales Total Chart Run,28 February 2007 Oricon Weekly Singles Chart W...,arts,Real Voice Charts Charts Release Chart Peak Po...
...,...,...,...,...,...,...,...
1006,Go Tell It on the Mountain (album),,Track listing,Professional ratings Professional ratings Revi...,"Allmusic, Allmusic link",arts,Go Tell It on the Mountain (album) Track list...
1007,Atom Bomb (album),,Track listing,Professional ratings Professional ratings Revi...,"Allmusic, Allmusic Rolling Stone, Rolling Stone",arts,Atom Bomb (album) Track listing Professional ...
1008,Claire Holt,Filmography,Filmography,Year Title Role Notes,"2006â€“2008 H2O: Just Add Water, H2O: Just Add...",arts,Claire Holt Filmography Filmography Year Title...
1009,Last Light (album),,Track listing,Professional ratings Professional ratings Revi...,"Allmusic, Allmusic Pitchfork Media, Pitchfork...",arts,Last Light (album) Track listing Professional...
1010,1988 World Rally Championship season,Teams and Drivers,Teams and Drivers,Team Constructor Car Tyre Drivers Rounds,"Martini Lancia, Martini Racing Lancia, Lancia ...",sports,1988 World Rally Championship season Teams and...

In [ ]:
# wiki_table_df[4]